<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_title</name>
   <tag></tag>
   <elementGuidId>a3e4e0ca-e747-4f16-8b99-93f5404daf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//marquee[@class='heading3']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
